name: Gitflow

on:
  pull_request:

jobs:
  gitflow:
    runs-on: ubuntu-latest

    steps:
      - name: debug
        run: |
          echo ${{github.ref}}
          echo ${{github.base_ref}}
          echo ${{github.head_ref}}

      - name: block-merge-on-main
        if: ${{github.base_ref == 'main'}}
        run: |
          if [[ ${{github.head_ref}} == refs/heads/develop ]] || [[ ${{github.head_ref}} == refs/heads/hotfix* ]]; then
            echo "::success Merge allowed"
            exit 0
          fi
          echo "::error Merge to main are only allowed from the develop branch or an hotfix branch"
          exit 1


      - name: block-merge-on-prod
        if: ${{github.base_ref == 'prod'}}
        run: |
          if [[ ${{github.head_ref}} == refs/heads/main ]] || [[ ${{github.head_ref}} == refs/heads/hotfix* ]]; then
            echo "::success Merge allowed"
            exit 0
          fi
          echo "::error Merge to prod are only allowed from the develop branch or an hotfix branch"
          exit 1

      - name: success
        run: |
          echo "::success Merge allowed"
          exit 0
